export { default as AddAuthor} from './AddAuthorForm.vue'
export {default as AuthorInfo} from './AuthorInfo.vue'
export {default as AuthorsTable} from './AuthorsTable.vue'


// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'