export {default as LoginForm} from './LoginForm.vue'
export {default as RegisterForm} from './RegisterForm.vue'
export {default as AddUserForm} from './AddUserForm.vue'
export {default as UsersTable} from './UsersTable.vue'
export {default as UserConfiguration} from './UserConfiguration.vue'
export {default as UserLogedEditForm} from './UserLogedEditForm.vue'
