export {default as AddBookForm} from './AddBookForm.vue'
export {default as BookForm} from './BookForm.vue'
export {default as BookInfo} from './BookInfo.vue'
export {default as BookInfoByAuthor} from './BookInfoByAuthor.vue'
export {default as CollectionBooks} from './CollectionBooks.vue'


// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'
// export {default as } from './.vue'